"""
Файл с ошибками приложения
"""


class InternalError(Exception):
    pass
